### ISSUE TITLE
function missing: dropsim_parameter

### ISSUE THREAD

**Issue by chelseaju** [marchinilab/dropsim#1]
Hi @daniel-wells, thank you for developing such a useful tool. I have been looking for simulator specifically for droplet-based single cell sequencing. When I tried to run your method, I noticed that the first step setting up the parameter is missing (dropsim_parameter). Any idea?

It seems to me that this tool output a DGE. What would be your suggestion to use the DGE to simulate reads?

Thanks,
Chelsea

**Comment by daniel-wells** [comment]
Hi @chelseaju, thanks for giving it a spin!

Sorry about your problem, I had forgotten to export that function (class). If you re-install it should work now!

You're correct in thinking this tool just deals at the count level. I'm not aware of anything that will take DGE and generate reads, perhaps you could look at the polyester package?

**Comment by chelseaju** [comment]
Hi @daniel-wells, thanks for your prompt response. I updated the software, and ran the following command lines:
```
library("dropsim")
packageVersion("dropsim")
new_parameters <- dropsim_parameters()
```
It shows that the library is now at version 1.0.1, but still complains that "could not find function "dropsim_parameters"".  Shall I call the function differently?

**Comment by daniel-wells** [comment]
oh sorry! 🤦‍♂️ It should be working now if you reinstall.

**Comment by chelseaju** [comment]
Thank you, @daniel-wells!! It works now. Interestingly, I had to reinstall devtools to download the new dropsim.
